upgrade additional dependencies
* pytest-selenium, because older version did not work:
    AttributeError: 'Config' object has no attribute '_environment'
* debian and java because hawtio is not compatible with java 7 anymore
* pytest-xdist because I can